id = "sql"
name = "SQL"
version = "1.1.1"
authors = ["evrsen"]
description = "SQL language support for Zed"
repository = "https://github.com/evrensen467/zed-sql"
schema_version = 1

[grammars.sql]
repository = "https://github.com/evrensen467/tree-sitter-sql"
commit = "6dfca8b6dcb196d943c10e9cabab25e60232d332"
